In [2]:
%run data.ipynb

['https://ltafarecard.s3.ap-southeast-1.amazonaws.com/202409/origin_destination_bus_202409.zip?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEN7%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLXNvdXRoZWFzdC0xIkYwRAIgNaqudLPKILNhqYzb3T5E38bNn%2FDjqx3QYvcf6AfJzQ8CIBrOBwoBmAJMbi6jb38ED2u%2BCSqrr5SXTb1Ra73VZDECKsIFCEcQBBoMMzQwNjQ1MzgxMzA0IgxnsvSt3uNJVaWgFcUqnwXCU28nWIjFL6QYyswpgoHO9ZpKFqFWuB%2FFheTc3xVsrzpLKnYT6rr3njPa%2B9vSKacT4Z7AB62iiOpgdNk6rywPl2nTEW%2BONOfbXQL85OpioUX5y8jGzMWeghIaJhHYrM0jhy7rA7qsU8xT%2FFQLGzlgZlliAtTi2EB7rTBdZL83pGt4ZqMdHF%2FyqeKXb63k67l1dglW4Uyk122y06vlD9bwepqhpcAiuowltugJUqaaPrCe2LuGt7ZsQh8Bz9h%2FnBj0pvPZcnU2WNmdetDrKBvXTqaUpOpwHq0QlhuqLejCKHtMcDF4fcyoDQ7QK9BU38LOUuJ%2BCgpTFb0loJu2mNG2fgazgRc4C2LAAD4XKHSwRxV3OpWlkHkfBzI%2FMiI2MiOzVFsfYbqrwVN76gR%2B8b3rAeRdVNou6ECWNXq9QcdOoSJ2QnifjCoEQy%2Be44B88KdWXbqOVqvsBKPvAWzox%2B27h1c9ADeD%2BfPGGdaPFWjLbXRWv%2Bujpp8qEPv95CTSI7ZnYf5X3pQTU6HQe%2BsGyvYCioWcpcaOtrlfpm4wY7k0IpvYkK3uoupIyo%2FxBnjo1t2823WW39pMN6K1lUcbyZKZQEgGLT8vca8gi4x98EYOlZ9oW2lbsGtv%2F%2FmGv5AxzHje7cD7ryOqZA1Af9wqAu5yBQao2URGXJ%2F6v99LX6y7ghTJAa5jx%2FPWjEpGMuFMlOh4%2BAawODXUGfdoQ2WNgQH6Qylw0%2BCBhow58TTCyI2TPS%2B92xg%2Bh%2FWfzUOSS6PCYgdrAcwyDqyOLyIcpsW4orv2Nd3q7xrsAI0jGzQn6ygs%2BtIMOnE9u46WKlEktTrqu3uELE1ivKoMW2JTbAyAEYdCR3suJXVb0lSvCZq8iGKouw3euQz%2FSr4pdIBNVgJC5TCR1sm4BjqyAQk9rLiU%2B8GbG3WBrRFetCQku4UGyoS2DsKSf4KaFQlyGMH1odjF89TYFk%2BzV3fYQJpIPWgxHNm6be0R3A9sayOLdtD0moU%2FmyETveBx4pRDKUeDj7RNxvmoMIto3rHrZCYBpzj8RGlNVJmHoU6EjLJvU27SEqYmIcl%2BApLFDdI0ovYVL70%2B1JYwroi9%2BGaqoFIYz%2FQOUhLcagw6Lg6q3CQpUSKh4kqVwdgv6LvMqSIZTXc%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241018T151842Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAU6UAMAS4NEOIBKGI%2F20241018%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Signature=c96124cf264e95c4205f5572902399154f843cb33172e27146fe5d94c8ed452a']
['https://ltafarecard.s3.ap-southeast-1.amazonaws.com/202409/origin_destination_train_202409.zip?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEN7%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLXNvdXRoZWFzdC0xIkYwRAIgNaqudLPKILNhqYzb3T5E38bNn%2FDjqx3QYvcf6AfJzQ8CIBrOBwoBmAJMbi6jb38ED2u%2BCSqrr5SXTb1Ra73VZDECKsIFCEcQBBoMMzQwNjQ1MzgxMzA0IgxnsvSt3uNJVaWgFcUqnwXCU28nWIjFL6QYyswpgoHO9ZpKFqFWuB%2FFheTc3xVsrzpLKnYT6rr3njPa%2B9vSKacT4Z7AB62iiOpgdNk6rywPl2nTEW%2BONOfbXQL85OpioUX5y8jGzMWeghIaJhHYrM0jhy7rA7qsU8xT%2FFQLGzlgZlliAtTi2EB7rTBdZL83pGt4ZqMdHF%2FyqeKXb63k67l1dglW4Uyk122y06vlD9bwepqhpcAiuowltugJUqaaPrCe2LuGt7ZsQh8Bz9h%2FnBj0pvPZcnU2WNmdetDrKBvXTqaUpOpwHq0QlhuqLejCKHtMcDF4fcyoDQ7QK9BU38LOUuJ%2BCgpTFb0loJu2mNG2fgazgRc4C2LAAD4XKHSwRxV3OpWlkHkfBzI%2FMiI2MiOzVFsfYbqrwVN76gR%2B8b3rAeRdVNou6ECWNXq9QcdOoSJ2QnifjCoEQy%2Be44B88KdWXbqOVqvsBKPvAWzox%2B27h1c9ADeD%2BfPGGdaPFWjLbXRWv%2Bujpp8qEPv95CTSI7ZnYf5X3pQTU6HQe%2BsGyvYCioWcpcaOtrlfpm4wY7k0IpvYkK3uoupIyo%2FxBnjo1t2823WW39pMN6K1lUcbyZKZQEgGLT8vca8gi4x98EYOlZ9oW2lbsGtv%2F%2FmGv5AxzHje7cD7ryOqZA1Af9wqAu5yBQao2URGXJ%2F6v99LX6y7ghTJAa5jx%2FPWjEpGMuFMlOh4%2BAawODXUGfdoQ2WNgQH6Qylw0%2BCBhow58TTCyI2TPS%2B92xg%2Bh%2FWfzUOSS6PCYgdrAcwyDqyOLyIcpsW4orv2Nd3q7xrsAI0jGzQn6ygs%2BtIMOnE9u46WKlEktTrqu3uELE1ivKoMW2JTbAyAEYdCR3suJXVb0lSvCZq8iGKouw3euQz%2FSr4pdIBNVgJC5TCR1sm4BjqyAQk9rLiU%2B8GbG3WBrRFetCQku4UGyoS2DsKSf4KaFQlyGMH1odjF89TYFk%2BzV3fYQJpIPWgxHNm6be0R3A9sayOLdtD0moU%2FmyETveBx4pRDKUeDj7RNxvmoMIto3rHrZCYBpzj8RGlNVJmHoU6EjLJvU27SEqYmIcl%2BApLFDdI0ovYVL70%2B1JYwroi9%2BGaqoFIYz%2FQOUhLcagw6Lg6q3CQpUSKh4kqVwdgv6LvMqSIZTXc%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241018T151849Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAU6UAMAS4NEOIBKGI%2F20241018%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Signature=eeeecdbf60c1d3e36f10b445b4c540f99789e80f660217187f1049cc5999ebe8']

In [3]:
# bus stops geodataframe
bus_stops_gdf = geopandas.GeoDataFrame(bus_stops, 
                                       geometry = geopandas.points_from_xy(bus_stops.Longitude, bus_stops.Latitude),
                                       crs = "EPSG:4326")
bus_stops_gdf

,BusStopCode,RoadName,Description,Latitude,Longitude,geometry
0,01012,Victoria St,Hotel Grand Pacific,1.296848,103.852536,POINT (103.85254 1.29685)
1,01013,Victoria St,St. Joseph's Ch,1.297710,103.853225,POINT (103.85322 1.29771)
2,01019,Victoria St,Bras Basah Cplx,1.296990,103.853022,POINT (103.85302 1.29699)
3,01029,Nth Bridge Rd,Opp Natl Lib,1.296673,103.854414,POINT (103.85441 1.29667)
4,01039,Nth Bridge Rd,Bugis Cube,1.298208,103.855491,POINT (103.85549 1.29821)
...,...,...,...,...,...,...
5133,99139,Changi Village Rd,Blk 5,1.388195,103.987234,POINT (103.98723 1.38819)
5134,99161,Nicoll Dr,Aft Changi Beach CP 3,1.390262,103.992957,POINT (103.99296 1.39026)
5135,99171,Nicoll Dr,Changi Beach CP 2,1.391128,103.991021,POINT (103.99102 1.39113)
5136,99181,Telok Paku Rd,Bef S'pore Aviation Ac,1.387754,103.988503,POINT (103.9885 1.38775)
5137,99189,Telok Paku Rd,S'pore Aviation Ac,1.388414,103.989716,POINT (103.98972 1.38841)

In [4]:
# bus routes geodataframe
bus_routes_gdf = geopandas.GeoDataFrame(bus_route_names, 
                                       geometry = geopandas.points_from_xy(bus_route_names.Longitude, bus_route_names.Latitude),
                                       crs = "EPSG:4326")
bus_routes_gdf

,ServiceNo,Operator,Direction,StopSequence,BusStopCode,Distance,WD_FirstBus,WD_LastBus,SAT_FirstBus,SAT_LastBus,SUN_FirstBus,SUN_LastBus,RoadName,Description,Latitude,Longitude,geometry
0,10,SBST,1,1,75009,0.0,0500,2300,0500,2300,0500,2300,Tampines Ctrl 1,Tampines Int,1.354076,103.943391,POINT (103.94339 1.35408)
1,10,SBST,1,2,76059,0.6,0502,2302,0502,2302,0502,2302,Tampines Ave 5,Opp Our Tampines Hub,1.352962,103.941652,POINT (103.94165 1.35296)
2,10,SBST,1,3,76069,1.1,0504,2304,0504,2304,0503,2304,Tampines Ave 5,Blk 147,1.348753,103.942086,POINT (103.94209 1.34875)
3,10,SBST,1,4,96289,2.3,0508,2308,0508,2309,0507,2308,Simei Ave,Changi General Hosp,1.340055,103.948381,POINT (103.94838 1.34005)
4,10,SBST,1,5,96109,2.7,0509,2310,0509,2311,0508,2309,Simei Ave,Opp Blk 3012,1.337371,103.950673,POINT (103.95067 1.33737)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25539,9B,SBST,1,25,95091,9.5,0741,0817,-,-,-,-,Nicoll Dr,SAF Ferry Ter,1.387214,103.999714,POINT (103.99971 1.38721)
25540,9B,SBST,1,26,95131,9.7,0742,0818,-,-,-,-,Airline Rd,Police Pass Off,1.385252,103.999834,POINT (103.99983 1.38525)
25541,9B,SBST,1,27,95141,10.2,0744,0820,-,-,-,-,Airline Rd,Aft Cargo Bldg D,1.381386,103.998191,POINT (103.99819 1.38139)
25542,9B,SBST,1,28,95061,10.6,0745,0821,-,-,-,-,Airline Rd,Airline Hse,1.377552,103.996539,POINT (103.99654 1.37755)
25543,9B,SBST,1,29,95051,11.0,0747,0823,-,-,-,-,Airline Rd,3rd Cargo Agents,1.375283,103.996196,POINT (103.9962 1.37528)

In [5]:
# train station exits geodataframe
train_station_exits_gdf = geopandas.read_file('./TrainStationExit/Train_Station_Exit_Layer.shp')
train_station_exits_gdf

                       stn_name exit_code                     geometry
0        MACPHERSON MRT STATION    Exit A  POINT (34285.068 34322.985)
1        MACPHERSON MRT STATION    Exit B  POINT (34382.153 34231.904)
2        MACPHERSON MRT STATION    Exit C  POINT (34337.292 34190.603)
3          TONGKANG LRT STATION    Exit B  POINT (33872.145 41256.053)
4          TONGKANG LRT STATION    Exit A  POINT (33858.542 41234.065)
..                          ...       ...                          ...
588        BAYSHORE MRT STATION    Exit 2  POINT (39947.586 32720.398)
589        BAYSHORE MRT STATION    Exit 3  POINT (39952.869 32873.448)
590        BAYSHORE MRT STATION    Exit 4  POINT (40170.433 32868.859)
591        BAYSHORE MRT STATION    Exit 5  POINT (40160.253 32799.231)
592  TANJONG KATONG MRT STATION    Exit 3  POINT (35166.777 31398.349)

[593 rows x 3 columns]

In [6]:
bus_routes_gdf_3857 = bus_routes_gdf.to_crs(3857)
train_station_exits_gdf_3857 = train_station_exits_gdf.to_crs(3857)

nearest_train_station_output = []
for i, row in tqdm(bus_routes_gdf_3857.iterrows()):

    # Compute the distance from each bus stop to all train station exits
    distances = train_station_exits_gdf_3857.distance(row['geometry'])

    nearest_train_station_output.append({
        'Bus Service': row['ServiceNo'],
        'Route Direction': row['Direction'],
        'Bus Stop Code': row['BusStopCode'],
        'Description': row['Description'],
        'Nearest Train Station': train_station_exits_gdf_3857.loc[int(distances.argmin()), 'stn_name'],
        'Distance': float(distances.min())
    })

nearest_train_stations = pd.DataFrame(nearest_train_station_output)
nearest_train_stations

25544it [00:20, 1266.06it/s]

,Bus Service,Route Direction,Bus Stop Code,Description,Nearest Train Station,Distance
0,10,1,75009,Tampines Int,TAMPINES MRT STATION,83.128361
1,10,1,76059,Opp Our Tampines Hub,TAMPINES MRT STATION,176.842601
2,10,1,76069,Blk 147,TAMPINES WEST MRT STATION,544.757282
3,10,1,96289,Changi General Hosp,SIMEI MRT STATION,671.311993
4,10,1,96109,Opp Blk 3012,SIMEI MRT STATION,685.307682
...,...,...,...,...,...,...
25539,9B,1,95091,SAF Ferry Ter,CHANGI AIRPORT MRT STATION,3614.202233
25540,9B,1,95131,Police Pass Off,CHANGI AIRPORT MRT STATION,3418.887434
25541,9B,1,95141,Aft Cargo Bldg D,CHANGI AIRPORT MRT STATION,2951.221627
25542,9B,1,95061,Airline Hse,CHANGI AIRPORT MRT STATION,2486.380997
25543,9B,1,95051,3rd Cargo Agents,CHANGI AIRPORT MRT STATION,2241.673779

In [16]:
bus_stops_with_mrt = nearest_train_stations[nearest_train_stations['Distance'] < 150]
number_of_mrt = bus_stops_with_mrt.groupby(['Bus Service', 'Route Direction']).size().reset_index(name = 'Count')
number_of_mrt.sort_values('Count', ascending = False)

    Bus Service  Route Direction  Count
342          36                1     29
433          63                1     28
670        972M                1     27
344         36B                1     26
468          67                1     24
..          ...              ...    ...
662         96A                1      1
692        983A                1      1
695         98A                1      1
696         98B                1      1
22         109A                1      1

[710 rows x 3 columns]

In [20]:
bus_stops_with_mrt[bus_stops_with_mrt['Bus Service'] == "960"]

,Bus Service,Route Direction,Bus Stop Code,Description,Nearest Train Station,Distance
12847,36,1,95129,Changi Airport Ter 2,CHANGI AIRPORT MRT STATION,139.159048
12852,36,1,93039,Siglap Stn/Laguna Park,SIGLAP MRT STATION,108.461316
12853,36,1,93201,Victoria Sch,SIGLAP MRT STATION,107.411983
12856,36,1,92089,Marine Terr Stn/Katong Convent,MARINE TERRACE MRT STATION,67.920836
12857,36,1,92079,Marine Terr Stn Exit 1,MARINE TERRACE MRT STATION,81.101982
12859,36,1,92059,Marine Pde Stn Exit 6,MARINE PARADE MRT STATION,36.950814
12860,36,1,92049,Marine Pde Stn/Parkway Pde,MARINE PARADE MRT STATION,67.141553
12863,36,1,82059,Bef Tg Katong Stn Exit 3,TANJONG KATONG MRT STATION,132.663901
12867,36,1,02171,Opp The Ritz-Carlton,PROMENADE MRT STATION,115.988685
12870,36,1,04111,Capitol Bldg,CITY HALL MRT STATION,72.054442
12871,36,1,04121,SMU,BRAS BASAH MRT STATION,100.717207
12872,36,1,08041,YMCA,DHOBY GHAUT MRT STATION,119.344764
12873,36,1,08031,Dhoby Ghaut Stn Exit B,DHOBY GHAUT MRT STATION,82.938399
12874,36,1,08111,Winsland Hse,SOMERSET MRT STATION,140.205398
12875,36,1,08121,Somerset Stn,SOMERSET MRT STATION,17.913349
12877,36,1,09022,ORCHARD STN EXIT 13,ORCHARD MRT STATION,39.681403
12883,36,1,09047,Orchard Stn/Tang Plaza,ORCHARD MRT STATION,38.070602
12886,36,1,08057,Dhoby Ghaut Stn,DHOBY GHAUT MRT STATION,29.086121
12887,36,1,08069,Bencoolen Stn Exit B,BENCOOLEN MRT STATION,22.232241
12888,36,1,04179,Aft Bras Basah Stn Exit A,BRAS BASAH MRT STATION,45.237309
12889,36,1,02049,Raffles Hotel,ESPLANADE MRT STATION,143.652875
12891,36,1,02161,Aft Promenade Stn Exit C,PROMENADE MRT STATION,112.176217
12892,36,1,82051,Aft Tg Katong Stn Exit 2,TANJONG KATONG MRT STATION,72.546471
12894,36,1,92041,Marine Pde Stn Exit 2,MARINE PARADE MRT STATION,43.515734
12895,36,1,92051,Marine Pde Stn Exit 4,MARINE PARADE MRT STATION,23.608254
12897,36,1,92071,Marine Terr Stn Exit 4,MARINE TERRACE MRT STATION,31.800688
12898,36,1,92081,St. Patrick's Sec Sch,MARINE TERRACE MRT STATION,51.177523
12905,36,1,95109,Changi Airport Ter 3,CHANGI AIRPORT MRT STATION,132.891017
12907,36,1,95129,Changi Airport Ter 2,CHANGI AIRPORT MRT STATION,139.159048